# Aakash Patel - pate2011
all:
	gcc tunneld.c invalid_password.c error_out.c error.c -g -o tunneld
	gcc tunnelcli.c invalid_password.c  error.c error_out.c -g -o tunnelcli
clean:
	rm -f tunneld tunnelcli
